"""add error_message to document_assessments

Revision ID: aa7cf7ecc463
Revises: f8c0acfdf899
Create Date: 2026-09-12 10:03:24.923462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7cf7ecc463'
down_revision: Union[str, Sequence[str], None] = 'f8c0acfdf899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_assessments', sa.Column('error_message', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_assessments', 'error_message')
    # ### end Alembic commands ###
