"""expand document_assessments for two-phase pipeline

Revision ID: f8c0acfdf899
Revises: ae0b314483c9
Create Date: 2026-09-12 00:45:31.250996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c0acfdf899'
down_revision: Union[str, Sequence[str], None] = 'ae0b314483c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows predate this migration (they came from the single-phase v1
    # flow) — default them to document_text='' / status='assessed' (they
    # already have a completed result) / extracted_context='{}' so the
    # NOT NULL columns can be added without breaking those rows.
    op.add_column('document_assessments', sa.Column('document_text', sa.Text(), nullable=False, server_default=''))
    op.add_column('document_assessments', sa.Column('status', sa.String(), nullable=False, server_default='assessed'))
    op.add_column('document_assessments', sa.Column('extracted_context', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('document_assessments', sa.Column('corrected_context', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_assessments', 'corrected_context')
    op.drop_column('document_assessments', 'extracted_context')
    op.drop_column('document_assessments', 'status')
    op.drop_column('document_assessments', 'document_text')
    # ### end Alembic commands ###
